version: '2.4'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: frontwit
    ports:
      - 27017:27017
    volumes:
      - "./administration/src/test/resources:/docker-entrypoint-initdb.d"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: frontwit
      MYSQL_USER: patryk
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - "./administration/src/test/resources:/docker-entrypoint-initdb.d"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

