version: '3'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: frontwit
    ports:
      - 27017:27017
    volumes:
      - "./:/docker-entrypoint-initdb.d"

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"

